# Bambu PLA Basic @BBL X1C
# Converted from OrcaSlicer by deli.
# note: Bed temperature taken from Orca's Textured PEI Plate values.
# note: additional_cooling_fan_speed (auxiliary fan) is not emitted by PrusaSlicer.
bed_temperature = 55
bridge_fan_speed = 100
chamber_temperature = 0
cooling = 1
disable_fan_first_layers = 1
end_filament_gcode = "; filament end gcode \n\n"
extrusion_multiplier = 0.98,0.98
fan_always_on = 1
fan_below_layer_time = 100
filament_cost = 24.99
filament_density = 1.26
filament_diameter = 1.75
filament_max_volumetric_speed = 21,21
filament_minimal_purge_on_wipe_tower = 15
filament_settings_id = Bambu PLA Basic @BBL X1C
filament_soluble = 0
filament_type = PLA
filament_vendor = Bambu Lab
first_layer_bed_temperature = 55
first_layer_temperature = 220,220
full_fan_speed_layer = 0
max_fan_speed = 100
min_fan_speed = 100
min_print_speed = 20
slowdown_below_layer_time = 4
start_filament_gcode = "; filament start gcode\n{if  (bed_temperature[current_extruder] >55)||(first_layer_bed_temperature[current_extruder] >55)}M106 P3 S200\n{elsif(bed_temperature[current_extruder] >50)||(first_layer_bed_temperature[current_extruder] >50)}M106 P3 S150\n{elsif(bed_temperature[current_extruder] >45)||(first_layer_bed_temperature[current_extruder] >45)}M106 P3 S50\n{endif}\nM142 P1 R35 S40\n{if false && true}\nM106 P3 S{178.5} \n{endif}"
temperature = 220,220
